apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: nginx-app
    releaseName: nginx-app
    namespace: default
    version: 0.1.0
    valuesFile: values.yaml
